export const WISHLIST_ADD_ITEM = "WISHLIST_ADD_ITEM";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
export const WISHLIST_ADD_TO_CART = "WISHLIST_ADD_TO_CART";
export const WISHLIST_DELETE_ALL = "WISHLIST_DELETE_ALL";
