export const AUTH_USER_LOADING = "AUTH_USER_LOADING";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_CLEAR = "AUTH_USER_CLEAR";
export const AUTH_USER_LOADING_OFF = "AUTH_USER_LOADING_OFF";
